# -*- coding: utf-8 -*-
"""Trabalho.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3f5ix4y-U9MYNk4Ih2ltkDIWLQaBIV4
"""

# Membros:
# Alexandre Augusto
# Felipe Yabiko      
# João Tapparo       
# Lucas Timponi     

#-----------------------------------------------------------------------
#                            EXERCICIO 1
#-----------------------------------------------------------------------

import numpy as np
import math as ma

v=np.array([0,0])

for i in range(2):
  print("Qual é o elemento na posição", i+1, "do vetor v? " )
  v[i]=float(input())


print("\nValores do vetor:")
print(v)

angulo = float(input("Qual é o valor do ângulo? "))
cosseno = np.cos(angulo)
seno = np.sin(angulo)
print(cosseno)
print(seno)

sentido = int(input("Deseja saber o sentido anti horario(1) ou horario(2)?"))
if sentido == 1:
  X = [cosseno * v[0] -seno * v[1]]
  Y = [seno * v[1] +cosseno * v[0]]
  print(X, Y)

elif sentido == 2:
  X = [cosseno * v[0] +seno * v[1]]
  Y = [-seno * v[1] +cosseno * v[0]]
  print(X, Y)

else:
  print("Digita 1 ou 2.")

#-----------------------------------------------------------------------
#                            EXERCICIO 2
#-----------------------------------------------------------------------

LA = int(input("Qual é o número de linhas da matriz A? "))
CA = int(input("Qual é o número de colunas da matriz A? "))
A=np.zeros((LA,CA))

LB = int(input("Qual é o número de linhas da matriz B? "))
CB = int(input("Qual é o número de colunas da matriz B? "))
B=np.zeros((LB,CB))

if CA == LB:
  print("O produto existe!")

  for i in range(LA):
    for j in range(CA):
      print("Digite o elemento da linha",i+1, "e coluna", j+1 )
      A[i,j]=float(input())

  for i in range(LB):
    for j in range(CB):
      print("Digite o elemento da linha",i+1, "e coluna", j+1 )
      B[i,j]=float(input())


  print(A@B)

else:
  print("O produto nao existe!")